### ISSUE TITLE
Database schema is out of sync with the model classes

### ISSUE THREAD

**Issue by mauler2025** [dotnet-presentations/aspnetcore-app-workshop#107]
The `Speaker` entity depicted in [The database schema](https://github.com/dotnet-presentations/aspnetcore-app-workshop/raw/master/docs/conference-planner-db-diagram.png) has `ConferenceID` but its correponding classes ([`ConferenceDTO.Speaker`](https://github.com/dotnet-presentations/aspnetcore-app-workshop/blob/master/src/ConferenceDTO/Speaker.cs) and [`BackEnd.Data.Speaker`](https://github.com/dotnet-presentations/aspnetcore-app-workshop/blob/master/src/BackEnd/Data/Speaker.cs)) have no such a property.

**Comment by ajcvickers** [comment]
@pstricks-fans Looks like it is a foreign key column which EF is managing in [shadow state](https://docs.microsoft.com/en-us/ef/core/modeling/shadow-properties#conventions).

**Comment by mauler2025** [comment]
Thank you very much @ajcvickers !


Having a property of type  `ICollection<Speaker>` in `Conference`  is sufficient for EF Core to make a relationship between `Conference` and `Speaker`.  A shadow foreign key `ConferenceID` is then automatically  generated.
