### ISSUE TITLE
What is this initialized yet mutable collection property for?

### ISSUE THREAD

**Issue by mauler2025** [dotnet-presentations/aspnetcore-app-workshop#108]
I found a suspicious property quoted from the [repository][2] as follows.

    public class Speaker : ConferenceDTO.Speaker
    {
        public virtual ICollection<SessionSpeaker> SessionSpeakers { get; set; } = new List<SessionSpeaker>();
    }

## Question

I don't understand why the initialized collection is made mutable?

  [1]: https://github.com/dotnet-presentations/aspnetcore-app-workshop
  [2]: https://github.com/dotnet-presentations/aspnetcore-app-workshop/blob/adac3b73f8050da128dcd84323aa74af18d7f2b8/src/BackEnd/Data/Speaker.cs#L9

**Comment by ajcvickers** [comment]
@pstricks-fans Curious why you closed this; I was also interested in the answer.

**Comment by mauler2025** [comment]
No special reason other than tired of waiting for responses. :-)
