### ISSUE TITLE
Create .NET 3.0 Branch, start update and migration

### ISSUE THREAD

**Issue by spboyer** [dotnet-presentations/aspnetcore-app-workshop#96]

**Comment by jongalloway** [comment]
This is already in progress: https://github.com/dotnet-presentations/aspnetcore-app-workshop/tree/3.0

**Comment by DamianEdwards** [comment]
yeah, @davidfowl and I just delivered the 3.0 version at NDC Oslo. Work is ongoing in the 3.0 branch.
